webtalk_init -webtalk_dir C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.sim/sim_1/behav/xsim/xsim.dir/sim_encryption_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 26 19:35:43 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174850471_1777489594_210672914_260" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "339e1271-d2ba-4350-b462-6a5d788e63c0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "36f29354a6e7439e9c07ae4b931e0094" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "96" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6568_KB" -context "xsim\\usage"
webtalk_transmit -clientid 12987309 -regid "174850471_1777489594_210672914_260" -xml C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.sim/sim_1/behav/xsim/xsim.dir/sim_encryption_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.sim/sim_1/behav/xsim/xsim.dir/sim_encryption_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.sim/sim_1/behav/xsim/xsim.dir/sim_encryption_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
