# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.cache/wt [current_project]
set_property parent.project_path C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/testfile1.coe
read_verilog -library xil_defaultlib {
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/C_RAM_control.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/PushButton_Left.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/PushButton_Right.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/PushButton_Up.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/clk_divider.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/display_control.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/encryption.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/sevensegment.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/transmitter.v
  C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/new/Top.v
}
read_ip -quiet C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/ip/Ciphertext_RAM/Ciphertext_RAM.xci
set_property used_in_implementation false [get_files -all c:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/ip/Ciphertext_RAM/Ciphertext_RAM_ooc.xdc]

read_ip -quiet C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/ip/Plaintext_ROM/Plaintext_ROM.xci
set_property used_in_implementation false [get_files -all c:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/sources_1/ip/Plaintext_ROM/Plaintext_ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/constrs_1/new/n4DDRfpga.xdc
set_property used_in_implementation false [get_files C:/Users/linyi/Documents/FPGA/Encryption_transmit/Encryption.srcs/constrs_1/new/n4DDRfpga.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
