# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/linyi/Documents/FPGA/Encryption/Encryption.srcs/sources_1/ip/Ciphertext_RAM/Ciphertext_RAM.xci
# IP: The module: 'Ciphertext_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/linyi/Documents/FPGA/Encryption/Encryption.srcs/sources_1/ip/Ciphertext_RAM/Ciphertext_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ciphertext_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/linyi/Documents/FPGA/Encryption/Encryption.srcs/sources_1/ip/Ciphertext_RAM/Ciphertext_RAM.xci
# IP: The module: 'Ciphertext_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/linyi/Documents/FPGA/Encryption/Encryption.srcs/sources_1/ip/Ciphertext_RAM/Ciphertext_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ciphertext_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
